In [6]:
import pandas as pd
import numpy as np
from kmodes.kmodes import KModes
import warnings
from IPython.display import display
warnings.filterwarnings("ignore")
pd.set_option('display.float_format', lambda x: '%.3f' % x)
SEED_VALUE = 202407
vehicles = pd.read_csv("data/4 - Veiculos - Dados.csv")

In [7]:

vehicles.drop(columns=['a'], inplace=True)
np.random.seed(SEED_VALUE)
km = KModes(n_clusters=10, init='Huang', n_init=10, verbose=1, random_state=SEED_VALUE)
clusters = km.fit_predict(vehicles)
vehicles['cluster'] = clusters
print(vehicles.head())
display(vehicles)

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 279, cost: 12648.0
Run 1, iteration: 2/100, moves: 95, cost: 12634.0
Run 1, iteration: 3/100, moves: 5, cost: 12634.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 209, cost: 12611.0
Run 2, iteration: 2/100, moves: 79, cost: 12584.0
Run 2, iteration: 3/100, moves: 13, cost: 12578.0
Run 2, iteration: 4/100, moves: 8, cost: 12578.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 179, cost: 12635.0
Run 3, iteration: 2/100, moves: 74, cost: 12598.0
Run 3, iteration: 3/100, moves: 26, cost: 12586.0
Run 3, iteration: 4/100, moves: 3, cost: 12586.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 262, cost: 12728.0
Run 4, iteration: 2/100, moves: 93, cost: 12718.0
Run 4, iteration: 3/100, moves: 5, cost: 12718.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 234, cost: 12801.0
Run 5, iteration: 2/100, moves: 49, cost: 12782.0
Run 5, iteration: 3/100, moves: 3, cost: 12782.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 6, iteration: 1/100, moves: 244, cost: 12633.0
Run 6, iteration: 2/100, moves: 97, cost: 12591.0
Run 6, iteration: 3/100, moves: 27, cost: 12581.0
Run 6, iteration: 4/100, moves: 2, cost: 12581.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 7, iteration: 1/100, moves: 272, cost: 12757.0
Run 7, iteration: 2/100, moves: 118, cost: 12709.0
Run 7, iteration: 3/100, moves: 24, cost: 12698.0
Run 7, iteration: 4/100, moves: 10, cost: 12697.0
Run 7, iteration: 5/100, moves: 0, cost: 12697.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 8, iteration: 1/100, moves: 301, cost: 12658.0
Run 8, iteration: 2/100, moves: 96, cost: 12608.0
Run 8, iteration: 3/100, moves: 68, cost: 12564.0
Run 8, iteration: 4/100, moves: 21, cost: 12564.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 9, iteration: 1/100, moves: 226, cost: 12662.0
Run 9, iteration: 2/100, moves: 65, cost: 12642.0
Run 9, iteration: 3/100, moves: 31, cost: 12633.0
Run 9, iteration: 4/100, moves: 2, cost: 12633.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 10, iteration: 1/100, moves: 202, cost: 12742.0
Run 10, iteration: 2/100, moves: 55, cost: 12712.0
Run 10, iteration: 3/100, moves: 29, cost: 12705.0
Run 10, iteration: 4/100, moves: 6, cost: 12703.0
Run 10, iteration: 5/100, moves: 0, cost: 12703.0
Best run was number 8
   Comp  Circ  DCirc  RadRa  PrAxisRa  MaxLRa  ScatRa  Elong  PrAxisRect  \
0    95    48     83    178        72      10     162     42          20
1    91    41     84    141        57       9     149     45          19
2   104    50    106    209        66      10     207     32          23
3    93    41     82    159        63       9     144     46          19
4    85    44     70    205       103      52     149     45          19

   MaxLRect  ScVarMaxis  ScVarmaxis  RaGyr  SkewMaxis  Skewmaxis  Kurtmaxis  \
0       159         176         379    184         70          6         16
1       143         170         330    158         72          9         14
2       158         223         635    220         73         14          9
3       143         160         309    127         63          6         10
4       144         241         325    188        127          9         11

   KurtMaxis  HollRa Class  cluster
0        187     197   van        1
1        189     199   van        0
2        188     196  saab        5
3        199     207   van        3
4        180     183   bus        0

,Comp,Circ,DCirc,RadRa,PrAxisRa,MaxLRa,ScatRa,Elong,PrAxisRect,MaxLRect,ScVarMaxis,ScVarmaxis,RaGyr,SkewMaxis,Skewmaxis,Kurtmaxis,KurtMaxis,HollRa,Class,cluster
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van,1
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van,0
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab,5
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van,3
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,93,39,87,183,64,8,169,40,20,134,200,422,149,72,7,25,188,195,saab,1
842,89,46,84,163,66,11,159,43,20,159,173,368,176,72,1,20,186,197,van,1
843,106,54,101,222,67,12,222,30,25,173,228,721,200,70,3,4,187,201,saab,6
844,86,36,78,146,58,7,135,50,18,124,155,270,148,66,0,25,190,195,saab,1
845,85,36,66,123,55,5,120,56,17,128,140,212,131,73,1,18,186,190,van,2